export const seedData = {
  states: [
    { code: 'TG', name: 'Telangana' },
    { code: 'AP', name: 'Andhra Pradesh' },
  ],
  districts: {
    TG: [
      { name: 'Adilabad', mandals: ['Adilabad', 'Boath', 'Echoda', 'Utnoor'] },
      { name: 'Bhadradri Kothagudem', mandals: ['Kothagudem', 'Bhadrachalam', 'Palwancha', 'Yellandu'] },
      { name: 'Hanumakonda', mandals: ['Hanumakonda', 'Kazipet', 'Hasanparthy'] },
      { name: 'Hyderabad', mandals: ['Ameerpet', 'Khairatabad', 'Secunderabad', 'Charminar', 'Golconda'] },
      { name: 'Jagtial', mandals: ['Jagtial', 'Korutla', 'Metpalli', 'Dharmapuri'] },
      { name: 'Jangaon', mandals: ['Jangaon', 'Palakurthi', 'Station Ghanpur'] },
      { name: 'Jayashankar Bhupalpally', mandals: ['Bhupalpally', 'Kataram', 'Mahadevpur'] },
      { name: 'Jogulamba Gadwal', mandals: ['Gadwal', 'Alampur', 'Ieeza'] },
      { name: 'Kamareddy', mandals: ['Kamareddy', 'Banswada', 'Yellareddy', 'Bhiknoor'] },
      { name: 'Karimnagar', mandals: ['Karimnagar', 'Huzurabad', 'Choppadandi', 'Manakondur'] },
      { name: 'Khammam', mandals: ['Khammam', 'Sathupalli', 'Madhira', 'Wyra'] },
      { name: 'Komaram Bheem Asifabad', mandals: ['Asifabad', 'Kagaznagar', 'Sirpur'] },
      { name: 'Mahabubabad', mandals: ['Mahabubabad', 'Dornakal', 'Maripeda'] },
      { name: 'Mahabubnagar', mandals: ['Mahabubnagar', 'Jadcherla', 'Devarkadra', 'Makthal'] },
      { name: 'Mancherial', mandals: ['Mancherial', 'Bellampalli', 'Chennur'] },
      { name: 'Medak', mandals: ['Medak', 'Narsapur', 'Ramayampet'] },
      { name: 'Medchal Malkajgiri', mandals: ['Medchal', 'Malkajgiri', 'Quthbullapur', 'Kukatpally', 'Uppal'] },
      { name: 'Mulugu', mandals: ['Mulugu', 'Venkatapur', 'Eturnagaram'] },
      { name: 'Nagarkurnool', mandals: ['Nagarkurnool', 'Kollapur', 'Kalwakurthy', 'Achampet'] },
      { name: 'Nalgonda', mandals: ['Nalgonda', 'Miryalaguda', 'Devarakonda', 'Nakrekal'] },
      { name: 'Narayanpet', mandals: ['Narayanpet', 'Makthal', 'Kosgi'] },
      { name: 'Nirmal', mandals: ['Nirmal', 'Bhainsa', 'Mudhole'] },
      { name: 'Nizamabad', mandals: ['Nizamabad', 'Armoor', 'Bodhan', 'Balkonda'] },
      { name: 'Peddapalli', mandals: ['Peddapalli', 'Ramagundam', 'Manthani'] },
      { name: 'Rajanna Sircilla', mandals: ['Sircilla', 'Vemulawada', 'Chandurthi'] },
      { name: 'Rangareddy', mandals: ['Shamshabad', 'Rajendranagar', 'Ibrahimpatnam', 'Chevella', 'Shadnagar'] },
      { name: 'Sangareddy', mandals: ['Sangareddy', 'Zahirabad', 'Patancheru', 'Narayankhed'] },
      { name: 'Siddipet', mandals: ['Siddipet', 'Gajwel', 'Dubbak', 'Husnabad'] },
      { name: 'Suryapet', mandals: ['Suryapet', 'Kodad', 'Huzurnagar', 'Tungaturthi'] },
      { name: 'Vikarabad', mandals: ['Vikarabad', 'Tandur', 'Pargi', 'Kodangal'] },
      { name: 'Wanaparthy', mandals: ['Wanaparthy', 'Pebbair', 'Srirangapur'] },
      { name: 'Warangal', mandals: ['Warangal', 'Narsampet', 'Wardhannapet'] },
      { name: 'Yadadri Bhuvanagiri', mandals: ['Bhuvanagiri', 'Alair', 'Choutuppal'] },
    ],
    AP: [
      { name: 'Alluri Sitharama Raju', mandals: ['Paderu', 'Araku Valley', 'Chintoor'] },
      { name: 'Anakapalli', mandals: ['Anakapalli', 'Narsipatnam', 'Chodavaram', 'Yelamanchili'] },
      { name: 'Ananthapuramu', mandals: ['Anantapur', 'Tadipatri', 'Rayadurg', 'Kalyandurg'] },
      { name: 'Annamayya', mandals: ['Rayachoti', 'Madanapalle', 'Rajampet'] },
      { name: 'Bapatla', mandals: ['Bapatla', 'Chirala', 'Repalle', 'Vemuru'] },
      { name: 'Chittoor', mandals: ['Chittoor', 'Nagari', 'Punganur', 'Kuppam'] },
      { name: 'Dr. B.R. Ambedkar Konaseema', mandals: ['Amalapuram', 'Kothapeta', 'Ramachandrapuram'] },
      { name: 'East Godavari', mandals: ['Rajahmundry', 'Kovvur', 'Nidadavole'] },
      { name: 'Eluru', mandals: ['Eluru', 'Nuzvid', 'Chintalapudi'] },
      { name: 'Guntur', mandals: ['Guntur', 'Tenali', 'Mangalagiri'] },
      { name: 'Kakinada', mandals: ['Kakinada', 'Peddapuram', 'Tuni', 'Prathipadu'] },
      { name: 'Krishna', mandals: ['Machilipatnam', 'Gudivada', 'Avanigadda', 'Gannavaram'] },
      { name: 'Kurnool', mandals: ['Kurnool', 'Adoni', 'Yemmiganur', 'Pattikonda'] },
      { name: 'Nandyal', mandals: ['Nandyal', 'Allagadda', 'Banaganapalle', 'Dhone'] },
      { name: 'NTR', mandals: ['Vijayawada', 'Nandigama', 'Jaggayyapeta', 'Mylavaram'] },
      { name: 'Palnadu', mandals: ['Narasaraopet', 'Chilakaluripet', 'Sattenapalle', 'Macherla'] },
      { name: 'Parvathipuram Manyam', mandals: ['Parvathipuram', 'Salur', 'Palakonda'] },
      { name: 'Prakasam', mandals: ['Ongole', 'Markapuram', 'Giddalur', 'Kanigiri'] },
      { name: 'SPSR Nellore', mandals: ['Nellore', 'Kavali', 'Kovur', 'Atmakur'] },
      { name: 'Sri Sathya Sai', mandals: ['Puttaparthi', 'Dharmavaram', 'Hindupur', 'Kadiri'] },
      { name: 'Srikakulam', mandals: ['Srikakulam', 'Amadalavalasa', 'Ichchapuram', 'Tekkali'] },
      { name: 'Tirupati', mandals: ['Tirupati', 'Srikalahasti', 'Chandragiri', 'Gudur'] },
      { name: 'Visakhapatnam', mandals: ['Visakhapatnam', 'Bheemunipatnam', 'Gajuwaka'] },
      { name: 'Vizianagaram', mandals: ['Vizianagaram', 'Bobbili', 'Cheepurupalli', 'Srungavarapukota'] },
      { name: 'West Godavari', mandals: ['Bhimavaram', 'Tadepalligudem', 'Tanuku', 'Narasapuram'] },
      { name: 'Y.S.R. Kadapa', mandals: ['Kadapa', 'Proddatur', 'Badvel', 'Pulivendula'] }
    ]
  }
}
